<?php

########################################################################
# Extension Manager/Repository config file for ext: "blsvsa2013"
#
# Auto generated by Extension Builder 2012-10-09
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Sportabzeichen online 2013',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Berti Golf, Martin Gonschor',
	'author_email' => 'berti.golf@blsv.de, martin.gonschor@blsv.de',
	'author_company' => 'BLSV, BLSV',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => 'fertig, bis auf bugs und design, Schnittstelle ',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.9.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
?>